# Generated by Django 4.2.1 on 2023-06-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionamiento_app', '0002_alter_reporte_options_reporte_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='calle',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='colonia',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='foto_problema',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
